# Playbook to dump postgresql databases and upload it into S3

---
- name: ansible pgsql dump
  hosts: pgsql
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/dump_pgsql.yml






